apiVersion: v1
kind: Service
metadata:
  name: app-bravo
  namespace: bravo-demo-dev
spec:
  type: ClusterIP
  selector:
    app: app-bravo
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
